### ISSUE TITLE
How can I update the it87/hwmon package? Gigabyte AB350M-D3H

### ISSUE THREAD

**Issue by RonGeorge** [kmwoley/unRAID-Tools#1]
Hi Kevin, found this from your blog. I'm stuck at the beginning of the tutorial. My motherboard is new (Mar2017) , but Groeck said that my chips are supported in the new version of it87/hwmon. I found someone post on their issues with an almost identical setup and asked how to update the package (https://github.com/groeck/it87/issues/43). I created an Ubuntu VM to try the commands but apparently those packages are disabled in VMs.

```
# sensors-detect revision 6284 (2015-05-31 14:00:33 +0200)
# System: Gigabyte Technology Co., Ltd. AB350M-D3H [Default string]
# Board: Gigabyte Technology Co., Ltd. AB350M-D3H-CF
# Kernel: 4.12.3-unRAID x86_64
# Processor: AMD Ryzen 5 1600 Six-Core Processor (23/1/1)
```

```
[ 9142.757674] it87: Found IT8733E chip at 0xa40, revision 2
[ 9142.757699] it87: Beeping is supported
[ 9142.758124] it87: Found IT8733E chip at 0xa60, revision 3
```

[Relevant thread on LimeTech forums](https://forums.lime-technology.com/topic/59370-cant-see-motherboard-or-cpu-temperaturesfan-speeds-using-amdgigabyte/)

**Comment by kmwoley** [comment]
Sorry, @RonGeorge - I don't know any magic here. It looks like the folks on the LimeTech forum are likely your best source of help.
